apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: slack-service
  namespace: keptn
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: keptn/slack-service:latest
            imagePullPolicy: Always
            env:
            - name: SLACK_WEBHOOK_URL
              value: "https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX"
            - name: INCLUDE_ATTACHMENT
              value: "true"
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: slack-subscription-new-artefact
  namespace: keptn
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: new-artefact
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: slack-service
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: slack-subscription-configuration-changed
  namespace: keptn
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: configuration-changed
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: slack-service
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: slack-subscription-deployment-finished
  namespace: keptn
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: deployment-finished
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: slack-service
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: slack-subscription-tests-finished
  namespace: keptn
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: tests-finished
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: slack-service
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: slack-subscription-evaluation-done
  namespace: keptn
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: evaluation-done
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: slack-service
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: slack-subscription-keptn
  namespace: keptn
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: keptn-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: slack-service
